apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: prod-nodepool
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["m"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: prod-class
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 24h # 30 * 24h = 720h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: prod-class
spec:
  amiFamily: AL2 # Amazon Linux 2
  role: "KarpenterNodeRole-WheelsEMI-prod-cluster" # replace with your cluster name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "WheelsEMI-prod-cluster" # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "WheelsEMI-prod-cluster" # replace with your cluster name
  amiSelectorTerms:
    #- id: "${ARM_AMI_ID}"
    - id: "ami-054ae3fd6109e75f6"   #change by seeing our existing AMI ID of nodes
#   - id: "${GPU_AMI_ID}" # <- GPU Optimized AMD AMI
#   - name: "amazon-eks-node-${K8S_VERSION}-*" # <- automatically upgrade when a new AL2 EKS Optimized AMI is released. This is unsafe for production workloads. Validate AMIs in lower environments before deploying them to production.
